//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Commentary
    {
        public int Id { get; set; }
        public int Debate_id { get; set; }
        public string User_username { get; set; }
        public string Date_created { get; set; }
        public string Comment { get; set; }
    }
}
