//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserVerification
    {
        public string UserEmail { get; set; }
        public bool Verified { get; set; }
        public string Code { get; set; }
    
        public virtual User User { get; set; }
    }
}
